[build-system]
requires = ["poetry-core>=1.3.2"]
build-backend = "poetry.core.masonry.api"

[tool]
  [tool.commitizen]
  version = "0.7.0"
  version_files = ["pyproject.toml:version"]

  [tool.poetry]
  name = "GitHub Starter Workflows"
  version = "0.7.0"
  description = "GitHub Actions Starter Workflows and Default Community Health Files"
  authors = ["Kurt von Laven <kurt.von.laven@gmail.com>"]
  license = "MIT"

  [tool.poetry.dependencies]
  # Keep in sync with .pre-commit-config.yaml and .tool-versions.
  python = "^3.11.0"

  [tool.poetry.dev-dependencies]
  commitizen = "^2.37.0" # Keep in sync with .pre-commit-config.yaml.
  pre-commit = "^2.20.0"
