[build-system]
requires = ["poetry-core>=1.5.0"]
build-backend = "poetry.core.masonry.api"

[tool]
  [tool.commitizen]
  version = "0.7.16"
  version_files = ["pyproject.toml:version"]
  major_version_zero = true

  [tool.poetry]
  name = "GitHub Starter Workflows"
  version = "0.7.16"
  description = "GitHub Actions Starter Workflows and Default Community Health Files"
  authors = ["Kurt von Laven <kurt.von.laven@gmail.com>"]
  license = "MIT"

  [tool.poetry.dependencies]
  # Keep in sync with .pre-commit-config.yaml and .tool-versions.
  python = "==3.11.2"

  [tool.poetry.dev-dependencies]
  commitizen = "==2.42.0" # Keep in sync with .pre-commit-config.yaml.
  pre-commit = "==3.0.3"
